server:
  port: 8084

spring:
  application:
    name: "kafka-stream-avro"
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: ${spring.application.name}
      client-id: ${spring.application.name}-stream
    properties:
      schema:
        registry:
          url: http://localhost:8081
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      specific:
        avro:
          reader: true
    listener:
      missing-topics-fatal: false

# Open up all Spring Boot Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always